---
title: "Meeting Notes"
author: "BZ"
date: "6/24/2020"
output: html_document
---


# Weekly progress

## Week 7/13/2020

   Run type 1 error simulation using real-data correlation structure
   
   + use a different sampling stretagy from last week
   + sample test statistics for both test set genes and background genes
      + sample all test statistics from only the test set 
      + sample all test statistics from only the back ground set
      + sample all test statistics from all the test statistics (permutation)
   + sample corresponding between gene correlations


## Week 7/6/2020

   Run type 1 error simulation using real-data correlation structure
    
   + Assume we have 1000 genes, 50 in the gene set and the rest not
   + Calculate gene-level test statistics for genes in the test set 
   + Sample 950 gene-level test statistics from above results with replacement
   + maintain the gene correlation as it is in the real data 
   + run simulations to generate type 1 error
   + Compare `meaca` with `MRGSE` and potentially `PLAGE`, `ORA` and `GSEA` etc.

## Week 6/29/2020

### Check this week
   + Check if `meaca` changed the direction of DE: if gene2 is down regulated, and 
   gene 1 is up regulated, then our method may neutralize the DE effect. One solution
   is to make the expression level of gene 2 to be all negative. <check if this is 
   implemented in `meaca`)
       - This is not done yet
   + Check if `CAMERA` used moderated-t test in Huntington's disease (if not, try
   to apply normal t test in real data analysis)
      - `CAMERA` use moderated-t test by default, and no other test is provided 
      by the original function
   + explore if standardization matters in real data analysis
   + Check how gene set in KEGG is derived (if possible)
   + Make the results reproducible
      - Yes

### Questions for next week

## Week 6/22/2020

  + Check real data analysis result: how did I get the results 
    + result is from http://bioconductor.org/packages/release/data/experiment/manuals/KEGGandMetacoreDzPathwaysGEO/man/KEGGandMetacoreDzPathwaysGEO.pdf
    + data provided by the authors of PADOG, who published a paper https://link.springer.com/article/10.1186/1471-2105-13-136 showing that downweighting 
    overlapping genes boosts performance.
    + `filteranot` function is used to remove duplicate probsets, basically first 
    fit a `limma` model, then match the probes with gene names, and keep only the 
    each probe having the smallest p-value if there are duplicates
  + Check how many samples are simulated in the `GB_revision` folder
    + 25 each arm, 50 totol